spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/JwtAppDb
    password: 4412199.Gmc
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      format_sql: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

SpringBootJwt:
  app:
    jwtSecret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    jwtExpirationMs: 86400000